name: Teste Relatorio

on:
  #workflow_dispatch: 

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Disparar Token de Relatorio
        env:
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          # ALTERADO: Apontando para o repositório do SIGE
          REPO_DESTINO: "operacoesicaiu/worker-zoho-integration" 
        run: |
          # O sed troca o evento padrão pelo de relatório
          sed -i 's/google_token_ready/report_token_ready/g' index.js
          node index.js
