name: Transfer Secrets
on: workflow_dispatch

jobs:
  copy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Transfer
        env:
          GH_TOKEN: ${{ secrets.TRANSFER_TOKEN }}
          DEST_REPO: "operacoesicaiu/icaiu-data"
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        run: |
          gh secret set GOOGLE_CLIENT_EMAIL --repo "$DEST_REPO" --body "$GOOGLE_CLIENT_EMAIL"
          gh secret set GOOGLE_PRIVATE_KEY --repo "$DEST_REPO" --body "$GOOGLE_PRIVATE_KEY"
